blueprint:
  name: Update temperature of the thermostat
  description: >
    Sets target temperature depending on secondary temperature sensor. Group multiple temperature sensors in a helper group and set
    device_class to temerature. Climate device will be set to auto or heat/cool mode.
  domain: automation
  input:
    climate_target:
      name: Thermostat
      description: Thermostat to be updated
      selector:
        entity:
          domain: climate
    t_current_target:
      name: T_curr
      description: Current temperature from sensor group
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_high_temperature:
      name: Target high temperature
      description: Target high temperature of the thermostat
      selector:
        number:
          min: 0
          max: 100
          step: 0.5
          unit_of_measurement: "°F"
      default: 73
    target_low_temperature:
      name: Target low temperature
      description: Target low temperature of the thermostat
      selector:
        number:
          min: 0
          max: 100
          step: 0.5
          unit_of_measurement: "°F"
      default: 70

variables:
  climate_target: !input climate_target
  t_current_target: !input t_current_target
  target_low_temperature: !input target_low_temperature
  target_high_temperature: !input target_high_temperature
  t_thermostat: "{{float(state_attr(climate_target,'current_temperature') , 0)}}"
  t_current: "{{float(states[t_current_target].state, 0) }}"


trigger:
  - platform: state
    entity_id: !input climate_target
    id: climate
  - platform: state
    entity_id: !input t_current_target
    id: temperature



action:
  - service: system_log.write
    data: 
      message: >
        Setting high temp to {{ target_high_temperature }} and low temp to {{ target_low_temperature }} 
        on {{ climate_target }}. Current thermostat temp is {{ t_thermostat }} and sensor value is {{ t_current }}.
        Setting {{ climate_target }} current temp to {{ t_current }}.
        level: info
        logger: blueprints.nevesenin.target_temperature_adjustment_with_additional_thermostat
  - service: climate.set_temperature
    data:
      target_temp_high: {{ target_high_temperature }}
      target_temp_low: {{ target_low_temperature }}
      current_temperature: {{ t_current }}
      hvac_mode: heat_cool
    target:
      entity_id: !input climate_target
  - service: climate.set_fan_mode
    data:
      fan_mode: auto
mode: queued
