blueprint:
  name: Update temperature of the thermostat
  domain: automation
  input:
    climate_target:
      name: Thermostat
      description: Thermostat to be updated
      selector:
        entity:
          domain:
          - climate
          multiple: false
    climate_mode:
      name: Thermostat Mode
      description: Mode setting for thermostat
      selector:
        select:
          options:
            - label: heat/cool
              value: auto
            - label: heat
              value: heat
            - label: cool
              value: cool
            - label: fan only
              value: fanonly
            - label: "off"
              value: "off"
          mode: dropdown
          multiple: false
    fan_mode:
      name: Thermostat Fan Mode
      description: Fan mode setting for thermostat
      selector:
        select:
          options:
            - label: auto
              value: "off"
            - label: low
              value: low
            - label: medium
              value: med
            - label: high
              value: high
          mode: dropdown
          multiple: false
    t_current_target:
      name: Temperature Sensor
      description: Temperature sensor or sensor group
      selector:
        entity:
          domain:
          - sensor
          multiple: false
    target_high_temp:
      name: Thermostat High Target Temp
      description: Target high temperature of the thermostat
      selector:
        number:
          min: 0
          max: 100
          step: 0.5
          unit_of_measurement: "°F"
      default: 73
    target_low_temp:
      name: Thermostat Low Target Temp
      description: Target low temperature of the thermostat on heat/cool (auto) mode
      selector:
        number:
          min: 0
          max: 100
          step: 0.5
          unit_of_measurement: "°F"
      default: 70
    target_temp:
      name: Thermostat Target Temp
      description: Target temperature of the thermostat in heat or cool mode
      selector:
        number:
          min: 0
          max: 100
          step: 0.5
          unit_of_measurement: "°F"
      default: 70
  source_url: https://raw.githubusercontent.com/timsayles1/ha-blueprints/main/update_temps.yaml
mode: queued
variables:
  climate_target: !input climate_target
  t_current_target: !input t_current_target
  t_thermostat: '{{float(state_attr(climate_target,''current_temperature'') , 0)}}'
  t_current: '{{float(states[t_current_target].state, 0) }}'
  target_mode: !input climate_mode
  target_fan: !input fan_mode
  target_low_temp: !input target_low_temp
  target_high_temp: !input target_high_temp
  target_temp: !input target_temp
trigger:
- platform: state
  entity_id: !input climate_target
  id: climate
- platform: state
  entity_id: !input t_current_target
  id: temperature
condition: []
action:
- choose:
  - conditions:
    - condition: template
      value_template: '{{ (t_current != t_thermostat) and (t_current  != 0) and (t_thermostat
        != 0) }}'
    sequence:
    - service: python_script.thermostat_update
      data_template:
        thermomode: 4
        thermozone: 0
        thermostat: !input climate_target
        sensor: !input t_current_target
        target_temp_high: !input target_high_temp
        target_temp_low: !input target_low_temp
        temperature: !input target_temp
        hvac_mode: !input climate_mode
        fan_mode: !input fan_mode
  default: []
